<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_v1_animales_list' => [[], ['_controller' => 'App\\Controller\\API\\AnimalesController::list'], [], [['text', '/api/v1/animales/']], [], [], []],
    'api_v1_animales_animal' => [['animal'], ['_controller' => 'App\\Controller\\API\\AnimalesController::detalle'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/api/v1/animales']], [], [], []],
    'api_v1_animales_crear' => [[], ['_controller' => 'App\\Controller\\API\\AnimalesController::crear'], [], [['text', '/api/v1/animales/']], [], [], []],
    'api_v1_animales_editar' => [['animal'], ['_controller' => 'App\\Controller\\API\\AnimalesController::editar'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/api/v1/animales']], [], [], []],
    'api_v1_animales_eliminar' => [['animal'], ['_controller' => 'App\\Controller\\API\\AnimalesController::borrar'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/api/v1/animales']], [], [], []],
    'app_animales' => [[], ['_controller' => 'App\\Controller\\AnimalesController::index'], [], [['text', '/animales']], [], [], []],
    'app_animales_borrar' => [['animal'], ['_controller' => 'App\\Controller\\AnimalesController::borrar'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/animales/borrar']], [], [], []],
    'app_animales_editar' => [['animal'], ['animal' => null, '_controller' => 'App\\Controller\\AnimalesController::editar'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/animales/editar']], [], [], []],
    'app_animales_guardar' => [['animal'], ['animal' => null, '_controller' => 'App\\Controller\\AnimalesController::guardar'], [], [['variable', '/', '[^/]++', 'animal', true], ['text', '/animales/guardar']], [], [], []],
    'app_default' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'app_gatitos' => [[], ['_controller' => 'App\\Controller\\DefaultController::gatitos'], [], [['text', '/gatitos']], [], [], []],
    'app_sitios' => [[], ['_controller' => 'App\\Controller\\SitiosController::index'], [], [['text', '/sitios']], [], [], []],
];
