<?php

namespace ContainerVmd8Kxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UCZ7frxService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.UCZ7frx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UCZ7frx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animal' => ['privates', '.errored..service_locator.UCZ7frx.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.UCZ7frx": it needs an instance of "App\\Entity\\Animal" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'animal' => 'App\\Entity\\Animal',
            'entityManager' => '?',
        ]);
    }
}
