<?php

namespace ContainerVmd8Kxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalesController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AnimalesController' shared autowired service.
     *
     * @return \App\Controller\AnimalesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AnimalesController'] = $instance = new \App\Controller\AnimalesController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\AnimalesController', $container));

        return $instance;
    }
}
