<?php

namespace ContainerVmd8Kxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimal2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.gvPlhrR.App\Entity\Animal' shared service.
     *
     * @return \App\Entity\Animal
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gvPlhrR": it needs an instance of "App\\Entity\\Animal" but this type has been excluded in "config/services.yaml".');
    }
}
