<?php

namespace ContainerVmd8Kxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSitiosRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SitiosRepository' shared autowired service.
     *
     * @return \App\Repository\SitiosRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SitiosRepository'] = new \App\Repository\SitiosRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
